version: "3"

services:
  web:
    build:
      context: .
    volumes:
      - .:/app
      # Prevent these directories from mounting so they're not shared between host OS and Docker
      - /app/node_modules/
      - /app/tmp/
      # Mount these upload directories so they persist between runs
      - web-traces:/home/osm/traces
      - web-images:/home/osm/images
      - ./docker/nginx:/etc/nginx/sites-enabled
    ports:
      - "3000:3000"
    command: bash -x /root/onboot.sh > /root/crontab.log 2>&1
    restart: always

volumes:
  web-traces:
  web-images:
